# This is a basic workflow to help you get started with Actions

name: PokemonsApp_github_actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:   
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Use Node.js
        with:
          node-version: '15'
      
      - name: Install dependencies
      - run: npm install
      
      - name: Run unit tests
      - run: npm run test
      
      - name: Run e2e test
      - run: npm run test:cypress
      
      - name: Run prettier
        run: npm run prettier
      
      - name: Rin lint
      - run: npm run lint


         
